Koala\Bundle\MercuryContentBundle\Document\Content:
    referenceable: true
    type: document
    id: path
    parentdocument: parent
    nodename: name
    node: node
    fields:
        regions:
            type: string
            assoc: ""
        options:
            type: string
            assoc: ""
        title: string
    referrers:
        routes:
            referencedBy: routeContent
            referringDocument: Symfony\Cmf\Bundle\RoutingExtraBundle\Document\Route
