parameters:
#    koala_mercury_content.example.class: Koala\Bundle\MercuryContentBundle\Example

services:
#    koala_mercury_content.example:
#        class: %koala_mercury_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
