parameters:
    koala_mercury_content.controller.class: Koala\Bundle\MercuryContentBundle\Controller\ContentController
    koala_mercury_content.default_template: KoalaMercuryContentBundle:Content:index.html.twig

services:
    koala_mercury_content.controller:
        class: %koala_mercury_content.controller.class%
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
            - @templating
            - %koala_mercury_content.default_template%
            - %koala_mercury_content.save_method%
